const CreatePatientFormValues = {
  patientUpdateStatus: "ADD",
  nationalId: "",
  subjectNumber: "",
  otherIdentifier: "",
  lastName: "",
  firstName: "",
  maidenName: "",
  streetAddress: "",
  city: "",
  primaryPhone: "",
  gender: "",
  birthDateForDisplay: "",
  commune: "",
  education: "",
  maritialStatus: "",
  nationality: "",
  healthDistrict: "",
  healthRegion: "",
  otherNationality: "",
  currentHospitalization: false,
  roomNumber: "",
  clinicalInformations: [],
  clinicalInformationOther: "",
  recentAntibiotherapy: false,
  recentAntibiotherapyList: [],
  currentAntibiotherapy: false,
  currentAntibiotherapyList: [],
  currentAntibiotherapyDuration: "",
  recentHospitalization: false,
  recentHospitalizationCount: "",
  recentInvasiveGestures: [],
  indwellingDevice: [],
  patientContact: {
    person: {
      firstName: "",
      lastName: "",
      primaryPhone: "",
      email: "",
    },
  },
};

export default CreatePatientFormValues;
